name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # 指定 Node.js 版本
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build

    # # 部署到服务器
    # - name: Upload to Deploy Server
    #   uses: appleboy/scp-action@master
    #   with:
    #     # 服务器域名
    #     host: ${{ secrets.SERVER_HOST }}
    #     # 服务器用户名
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     # 服务器密码
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     # 服务器端口
    #     port: ${{ secrets.SERVER_PORT }}
    #     # 指定上传的文件目录(项目配置的打包目录名称)
    #     source: './dist/*'
    #     # 指定上传服务器目录
    #     target: '/var/www/html'
    #     # 解压时覆盖现有文件
    #     overwrite: true
    #     # 删除指定数量的前导路径元素
    #     strip_components: 1

    # 部署到服务器
    - name: Upload to Deploy Server2
      uses: appleboy/scp-action@master
      with:
        # 服务器域名
        host: ${{ secrets.SERVER2_HOST }}
        # 服务器用户名
        username: ${{ secrets.SERVER2_USERNAME }}
        # 服务器密码
        password: ${{ secrets.SERVER2_PASSWORD }}
        # 服务器端口
        port: ${{ secrets.SERVER_PORT }}
        # 指定上传的文件目录(项目配置的打包目录名称)
        source: './dist/*'
        # 指定上传服务器目录
        target: '/usr/share/nginx/html'
        # 解压时覆盖现有文件
        overwrite: true
        # 删除指定数量的前导路径元素
        strip_components: 1
